/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StoresRouteImport } from './routes/stores'
import { Route as SimuladorRouteImport } from './routes/simulador'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as RealEstateRouteImport } from './routes/real-estate'
import { Route as PerfilRouteImport } from './routes/perfil'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as MapRouteImport } from './routes/map'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as ComunidadRouteImport } from './routes/comunidad'
import { Route as ComparadorRouteImport } from './routes/comparador'
import { Route as CalculadoraRouteImport } from './routes/calculadora'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LocalBusinessBarrio_slugRouteImport } from './routes/local-business/$barrio_slug'
import { Route as ListingIdRouteImport } from './routes/listing.$id'
import { Route as EventosBarrio_slugRouteImport } from './routes/eventos/$barrio_slug'

const StoresRoute = StoresRouteImport.update({
  id: '/stores',
  path: '/stores',
  getParentRoute: () => rootRouteImport,
} as any)
const SimuladorRoute = SimuladorRouteImport.update({
  id: '/simulador',
  path: '/simulador',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const RealEstateRoute = RealEstateRouteImport.update({
  id: '/real-estate',
  path: '/real-estate',
  getParentRoute: () => rootRouteImport,
} as any)
const PerfilRoute = PerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const MapRoute = MapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ComunidadRoute = ComunidadRouteImport.update({
  id: '/comunidad',
  path: '/comunidad',
  getParentRoute: () => rootRouteImport,
} as any)
const ComparadorRoute = ComparadorRouteImport.update({
  id: '/comparador',
  path: '/comparador',
  getParentRoute: () => rootRouteImport,
} as any)
const CalculadoraRoute = CalculadoraRouteImport.update({
  id: '/calculadora',
  path: '/calculadora',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LocalBusinessBarrio_slugRoute =
  LocalBusinessBarrio_slugRouteImport.update({
    id: '/local-business/$barrio_slug',
    path: '/local-business/$barrio_slug',
    getParentRoute: () => rootRouteImport,
  } as any)
const ListingIdRoute = ListingIdRouteImport.update({
  id: '/listing/$id',
  path: '/listing/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const EventosBarrio_slugRoute = EventosBarrio_slugRouteImport.update({
  id: '/eventos/$barrio_slug',
  path: '/eventos/$barrio_slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/calculadora': typeof CalculadoraRoute
  '/comparador': typeof ComparadorRoute
  '/comunidad': typeof ComunidadRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/map': typeof MapRoute
  '/onboarding': typeof OnboardingRoute
  '/perfil': typeof PerfilRoute
  '/real-estate': typeof RealEstateRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/simulador': typeof SimuladorRoute
  '/stores': typeof StoresRoute
  '/eventos/$barrio_slug': typeof EventosBarrio_slugRoute
  '/listing/$id': typeof ListingIdRoute
  '/local-business/$barrio_slug': typeof LocalBusinessBarrio_slugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/calculadora': typeof CalculadoraRoute
  '/comparador': typeof ComparadorRoute
  '/comunidad': typeof ComunidadRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/map': typeof MapRoute
  '/onboarding': typeof OnboardingRoute
  '/perfil': typeof PerfilRoute
  '/real-estate': typeof RealEstateRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/simulador': typeof SimuladorRoute
  '/stores': typeof StoresRoute
  '/eventos/$barrio_slug': typeof EventosBarrio_slugRoute
  '/listing/$id': typeof ListingIdRoute
  '/local-business/$barrio_slug': typeof LocalBusinessBarrio_slugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/calculadora': typeof CalculadoraRoute
  '/comparador': typeof ComparadorRoute
  '/comunidad': typeof ComunidadRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/map': typeof MapRoute
  '/onboarding': typeof OnboardingRoute
  '/perfil': typeof PerfilRoute
  '/real-estate': typeof RealEstateRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/simulador': typeof SimuladorRoute
  '/stores': typeof StoresRoute
  '/eventos/$barrio_slug': typeof EventosBarrio_slugRoute
  '/listing/$id': typeof ListingIdRoute
  '/local-business/$barrio_slug': typeof LocalBusinessBarrio_slugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/calculadora'
    | '/comparador'
    | '/comunidad'
    | '/forgot-password'
    | '/login'
    | '/map'
    | '/onboarding'
    | '/perfil'
    | '/real-estate'
    | '/register'
    | '/reset-password'
    | '/simulador'
    | '/stores'
    | '/eventos/$barrio_slug'
    | '/listing/$id'
    | '/local-business/$barrio_slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/calculadora'
    | '/comparador'
    | '/comunidad'
    | '/forgot-password'
    | '/login'
    | '/map'
    | '/onboarding'
    | '/perfil'
    | '/real-estate'
    | '/register'
    | '/reset-password'
    | '/simulador'
    | '/stores'
    | '/eventos/$barrio_slug'
    | '/listing/$id'
    | '/local-business/$barrio_slug'
  id:
    | '__root__'
    | '/'
    | '/calculadora'
    | '/comparador'
    | '/comunidad'
    | '/forgot-password'
    | '/login'
    | '/map'
    | '/onboarding'
    | '/perfil'
    | '/real-estate'
    | '/register'
    | '/reset-password'
    | '/simulador'
    | '/stores'
    | '/eventos/$barrio_slug'
    | '/listing/$id'
    | '/local-business/$barrio_slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CalculadoraRoute: typeof CalculadoraRoute
  ComparadorRoute: typeof ComparadorRoute
  ComunidadRoute: typeof ComunidadRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  MapRoute: typeof MapRoute
  OnboardingRoute: typeof OnboardingRoute
  PerfilRoute: typeof PerfilRoute
  RealEstateRoute: typeof RealEstateRoute
  RegisterRoute: typeof RegisterRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SimuladorRoute: typeof SimuladorRoute
  StoresRoute: typeof StoresRoute
  EventosBarrio_slugRoute: typeof EventosBarrio_slugRoute
  ListingIdRoute: typeof ListingIdRoute
  LocalBusinessBarrio_slugRoute: typeof LocalBusinessBarrio_slugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/stores': {
      id: '/stores'
      path: '/stores'
      fullPath: '/stores'
      preLoaderRoute: typeof StoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/simulador': {
      id: '/simulador'
      path: '/simulador'
      fullPath: '/simulador'
      preLoaderRoute: typeof SimuladorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/real-estate': {
      id: '/real-estate'
      path: '/real-estate'
      fullPath: '/real-estate'
      preLoaderRoute: typeof RealEstateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perfil': {
      id: '/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof PerfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/map': {
      id: '/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof MapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comunidad': {
      id: '/comunidad'
      path: '/comunidad'
      fullPath: '/comunidad'
      preLoaderRoute: typeof ComunidadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comparador': {
      id: '/comparador'
      path: '/comparador'
      fullPath: '/comparador'
      preLoaderRoute: typeof ComparadorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calculadora': {
      id: '/calculadora'
      path: '/calculadora'
      fullPath: '/calculadora'
      preLoaderRoute: typeof CalculadoraRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/local-business/$barrio_slug': {
      id: '/local-business/$barrio_slug'
      path: '/local-business/$barrio_slug'
      fullPath: '/local-business/$barrio_slug'
      preLoaderRoute: typeof LocalBusinessBarrio_slugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/listing/$id': {
      id: '/listing/$id'
      path: '/listing/$id'
      fullPath: '/listing/$id'
      preLoaderRoute: typeof ListingIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/eventos/$barrio_slug': {
      id: '/eventos/$barrio_slug'
      path: '/eventos/$barrio_slug'
      fullPath: '/eventos/$barrio_slug'
      preLoaderRoute: typeof EventosBarrio_slugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CalculadoraRoute: CalculadoraRoute,
  ComparadorRoute: ComparadorRoute,
  ComunidadRoute: ComunidadRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  MapRoute: MapRoute,
  OnboardingRoute: OnboardingRoute,
  PerfilRoute: PerfilRoute,
  RealEstateRoute: RealEstateRoute,
  RegisterRoute: RegisterRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SimuladorRoute: SimuladorRoute,
  StoresRoute: StoresRoute,
  EventosBarrio_slugRoute: EventosBarrio_slugRoute,
  ListingIdRoute: ListingIdRoute,
  LocalBusinessBarrio_slugRoute: LocalBusinessBarrio_slugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
