/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerifyEmailRouteImport } from './routes/verify-email'
import { Route as VenderRouteImport } from './routes/vender'
import { Route as SuscribirseRouteImport } from './routes/suscribirse'
import { Route as StoresRouteImport } from './routes/stores'
import { Route as SolicitudesRouteImport } from './routes/solicitudes'
import { Route as SimuladorRouteImport } from './routes/simulador'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as RealEstateRouteImport } from './routes/real-estate'
import { Route as PublicarRouteImport } from './routes/publicar'
import { Route as PlanesRouteImport } from './routes/planes'
import { Route as PerfilRouteImport } from './routes/perfil'
import { Route as PasantiasRouteImport } from './routes/pasantias'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as MisPropiedadesRouteImport } from './routes/mis-propiedades'
import { Route as MapRouteImport } from './routes/map'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as EmbajadorRouteImport } from './routes/embajador'
import { Route as ConectarAgenteRouteImport } from './routes/conectar-agente'
import { Route as ComunidadRouteImport } from './routes/comunidad'
import { Route as ComparadorRouteImport } from './routes/comparador'
import { Route as CalculadoraRouteImport } from './routes/calculadora'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AgentesRouteImport } from './routes/agentes'
import { Route as AfiliadoRouteImport } from './routes/afiliado'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PanelX9k2IndexRouteImport } from './routes/panel-x9k2/index'
import { Route as SuscripcionExitoRouteImport } from './routes/suscripcion/exito'
import { Route as SuscripcionCanceladaRouteImport } from './routes/suscripcion/cancelada'
import { Route as RealtorDashboardRouteImport } from './routes/realtor/dashboard'
import { Route as RealtorAgencyDashboardRouteImport } from './routes/realtor/agency-dashboard'
import { Route as RealtorAcceptInviteRouteImport } from './routes/realtor/accept-invite'
import { Route as PlanesListingMemberRouteImport } from './routes/planes_.listing-member'
import { Route as PlanesHotSpotRouteImport } from './routes/planes_.hot-spot'
import { Route as PlanesFeaturedRealtorRouteImport } from './routes/planes_.featured-realtor'
import { Route as PlanesDealRouteImport } from './routes/planes_.deal'
import { Route as NegociosUnirseRouteImport } from './routes/negocios/unirse'
import { Route as LoginVerificarRouteImport } from './routes/login_.verificar'
import { Route as LocalBusinessBarrio_slugRouteImport } from './routes/local-business/$barrio_slug'
import { Route as ListingIdRouteImport } from './routes/listing.$id'
import { Route as EventosBarrio_slugRouteImport } from './routes/eventos/$barrio_slug'
import { Route as AgentesRegistroRouteImport } from './routes/agentes_.registro'

const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const VenderRoute = VenderRouteImport.update({
  id: '/vender',
  path: '/vender',
  getParentRoute: () => rootRouteImport,
} as any)
const SuscribirseRoute = SuscribirseRouteImport.update({
  id: '/suscribirse',
  path: '/suscribirse',
  getParentRoute: () => rootRouteImport,
} as any)
const StoresRoute = StoresRouteImport.update({
  id: '/stores',
  path: '/stores',
  getParentRoute: () => rootRouteImport,
} as any)
const SolicitudesRoute = SolicitudesRouteImport.update({
  id: '/solicitudes',
  path: '/solicitudes',
  getParentRoute: () => rootRouteImport,
} as any)
const SimuladorRoute = SimuladorRouteImport.update({
  id: '/simulador',
  path: '/simulador',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const RealEstateRoute = RealEstateRouteImport.update({
  id: '/real-estate',
  path: '/real-estate',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicarRoute = PublicarRouteImport.update({
  id: '/publicar',
  path: '/publicar',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanesRoute = PlanesRouteImport.update({
  id: '/planes',
  path: '/planes',
  getParentRoute: () => rootRouteImport,
} as any)
const PerfilRoute = PerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => rootRouteImport,
} as any)
const PasantiasRoute = PasantiasRouteImport.update({
  id: '/pasantias',
  path: '/pasantias',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const MisPropiedadesRoute = MisPropiedadesRouteImport.update({
  id: '/mis-propiedades',
  path: '/mis-propiedades',
  getParentRoute: () => rootRouteImport,
} as any)
const MapRoute = MapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const EmbajadorRoute = EmbajadorRouteImport.update({
  id: '/embajador',
  path: '/embajador',
  getParentRoute: () => rootRouteImport,
} as any)
const ConectarAgenteRoute = ConectarAgenteRouteImport.update({
  id: '/conectar-agente',
  path: '/conectar-agente',
  getParentRoute: () => rootRouteImport,
} as any)
const ComunidadRoute = ComunidadRouteImport.update({
  id: '/comunidad',
  path: '/comunidad',
  getParentRoute: () => rootRouteImport,
} as any)
const ComparadorRoute = ComparadorRouteImport.update({
  id: '/comparador',
  path: '/comparador',
  getParentRoute: () => rootRouteImport,
} as any)
const CalculadoraRoute = CalculadoraRouteImport.update({
  id: '/calculadora',
  path: '/calculadora',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentesRoute = AgentesRouteImport.update({
  id: '/agentes',
  path: '/agentes',
  getParentRoute: () => rootRouteImport,
} as any)
const AfiliadoRoute = AfiliadoRouteImport.update({
  id: '/afiliado',
  path: '/afiliado',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PanelX9k2IndexRoute = PanelX9k2IndexRouteImport.update({
  id: '/panel-x9k2/',
  path: '/panel-x9k2/',
  getParentRoute: () => rootRouteImport,
} as any)
const SuscripcionExitoRoute = SuscripcionExitoRouteImport.update({
  id: '/suscripcion/exito',
  path: '/suscripcion/exito',
  getParentRoute: () => rootRouteImport,
} as any)
const SuscripcionCanceladaRoute = SuscripcionCanceladaRouteImport.update({
  id: '/suscripcion/cancelada',
  path: '/suscripcion/cancelada',
  getParentRoute: () => rootRouteImport,
} as any)
const RealtorDashboardRoute = RealtorDashboardRouteImport.update({
  id: '/realtor/dashboard',
  path: '/realtor/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const RealtorAgencyDashboardRoute = RealtorAgencyDashboardRouteImport.update({
  id: '/realtor/agency-dashboard',
  path: '/realtor/agency-dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const RealtorAcceptInviteRoute = RealtorAcceptInviteRouteImport.update({
  id: '/realtor/accept-invite',
  path: '/realtor/accept-invite',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanesListingMemberRoute = PlanesListingMemberRouteImport.update({
  id: '/planes_/listing-member',
  path: '/planes/listing-member',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanesHotSpotRoute = PlanesHotSpotRouteImport.update({
  id: '/planes_/hot-spot',
  path: '/planes/hot-spot',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanesFeaturedRealtorRoute = PlanesFeaturedRealtorRouteImport.update({
  id: '/planes_/featured-realtor',
  path: '/planes/featured-realtor',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanesDealRoute = PlanesDealRouteImport.update({
  id: '/planes_/deal',
  path: '/planes/deal',
  getParentRoute: () => rootRouteImport,
} as any)
const NegociosUnirseRoute = NegociosUnirseRouteImport.update({
  id: '/negocios/unirse',
  path: '/negocios/unirse',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginVerificarRoute = LoginVerificarRouteImport.update({
  id: '/login_/verificar',
  path: '/login/verificar',
  getParentRoute: () => rootRouteImport,
} as any)
const LocalBusinessBarrio_slugRoute =
  LocalBusinessBarrio_slugRouteImport.update({
    id: '/local-business/$barrio_slug',
    path: '/local-business/$barrio_slug',
    getParentRoute: () => rootRouteImport,
  } as any)
const ListingIdRoute = ListingIdRouteImport.update({
  id: '/listing/$id',
  path: '/listing/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const EventosBarrio_slugRoute = EventosBarrio_slugRouteImport.update({
  id: '/eventos/$barrio_slug',
  path: '/eventos/$barrio_slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentesRegistroRoute = AgentesRegistroRouteImport.update({
  id: '/agentes_/registro',
  path: '/agentes/registro',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/afiliado': typeof AfiliadoRoute
  '/agentes': typeof AgentesRoute
  '/blog': typeof BlogRoute
  '/calculadora': typeof CalculadoraRoute
  '/comparador': typeof ComparadorRoute
  '/comunidad': typeof ComunidadRoute
  '/conectar-agente': typeof ConectarAgenteRoute
  '/embajador': typeof EmbajadorRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/map': typeof MapRoute
  '/mis-propiedades': typeof MisPropiedadesRoute
  '/onboarding': typeof OnboardingRoute
  '/pasantias': typeof PasantiasRoute
  '/perfil': typeof PerfilRoute
  '/planes': typeof PlanesRoute
  '/publicar': typeof PublicarRoute
  '/real-estate': typeof RealEstateRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/simulador': typeof SimuladorRoute
  '/solicitudes': typeof SolicitudesRoute
  '/stores': typeof StoresRoute
  '/suscribirse': typeof SuscribirseRoute
  '/vender': typeof VenderRoute
  '/verify-email': typeof VerifyEmailRoute
  '/agentes/registro': typeof AgentesRegistroRoute
  '/eventos/$barrio_slug': typeof EventosBarrio_slugRoute
  '/listing/$id': typeof ListingIdRoute
  '/local-business/$barrio_slug': typeof LocalBusinessBarrio_slugRoute
  '/login/verificar': typeof LoginVerificarRoute
  '/negocios/unirse': typeof NegociosUnirseRoute
  '/planes/deal': typeof PlanesDealRoute
  '/planes/featured-realtor': typeof PlanesFeaturedRealtorRoute
  '/planes/hot-spot': typeof PlanesHotSpotRoute
  '/planes/listing-member': typeof PlanesListingMemberRoute
  '/realtor/accept-invite': typeof RealtorAcceptInviteRoute
  '/realtor/agency-dashboard': typeof RealtorAgencyDashboardRoute
  '/realtor/dashboard': typeof RealtorDashboardRoute
  '/suscripcion/cancelada': typeof SuscripcionCanceladaRoute
  '/suscripcion/exito': typeof SuscripcionExitoRoute
  '/panel-x9k2/': typeof PanelX9k2IndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/afiliado': typeof AfiliadoRoute
  '/agentes': typeof AgentesRoute
  '/blog': typeof BlogRoute
  '/calculadora': typeof CalculadoraRoute
  '/comparador': typeof ComparadorRoute
  '/comunidad': typeof ComunidadRoute
  '/conectar-agente': typeof ConectarAgenteRoute
  '/embajador': typeof EmbajadorRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/map': typeof MapRoute
  '/mis-propiedades': typeof MisPropiedadesRoute
  '/onboarding': typeof OnboardingRoute
  '/pasantias': typeof PasantiasRoute
  '/perfil': typeof PerfilRoute
  '/planes': typeof PlanesRoute
  '/publicar': typeof PublicarRoute
  '/real-estate': typeof RealEstateRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/simulador': typeof SimuladorRoute
  '/solicitudes': typeof SolicitudesRoute
  '/stores': typeof StoresRoute
  '/suscribirse': typeof SuscribirseRoute
  '/vender': typeof VenderRoute
  '/verify-email': typeof VerifyEmailRoute
  '/agentes/registro': typeof AgentesRegistroRoute
  '/eventos/$barrio_slug': typeof EventosBarrio_slugRoute
  '/listing/$id': typeof ListingIdRoute
  '/local-business/$barrio_slug': typeof LocalBusinessBarrio_slugRoute
  '/login/verificar': typeof LoginVerificarRoute
  '/negocios/unirse': typeof NegociosUnirseRoute
  '/planes/deal': typeof PlanesDealRoute
  '/planes/featured-realtor': typeof PlanesFeaturedRealtorRoute
  '/planes/hot-spot': typeof PlanesHotSpotRoute
  '/planes/listing-member': typeof PlanesListingMemberRoute
  '/realtor/accept-invite': typeof RealtorAcceptInviteRoute
  '/realtor/agency-dashboard': typeof RealtorAgencyDashboardRoute
  '/realtor/dashboard': typeof RealtorDashboardRoute
  '/suscripcion/cancelada': typeof SuscripcionCanceladaRoute
  '/suscripcion/exito': typeof SuscripcionExitoRoute
  '/panel-x9k2': typeof PanelX9k2IndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/afiliado': typeof AfiliadoRoute
  '/agentes': typeof AgentesRoute
  '/blog': typeof BlogRoute
  '/calculadora': typeof CalculadoraRoute
  '/comparador': typeof ComparadorRoute
  '/comunidad': typeof ComunidadRoute
  '/conectar-agente': typeof ConectarAgenteRoute
  '/embajador': typeof EmbajadorRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/map': typeof MapRoute
  '/mis-propiedades': typeof MisPropiedadesRoute
  '/onboarding': typeof OnboardingRoute
  '/pasantias': typeof PasantiasRoute
  '/perfil': typeof PerfilRoute
  '/planes': typeof PlanesRoute
  '/publicar': typeof PublicarRoute
  '/real-estate': typeof RealEstateRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/simulador': typeof SimuladorRoute
  '/solicitudes': typeof SolicitudesRoute
  '/stores': typeof StoresRoute
  '/suscribirse': typeof SuscribirseRoute
  '/vender': typeof VenderRoute
  '/verify-email': typeof VerifyEmailRoute
  '/agentes_/registro': typeof AgentesRegistroRoute
  '/eventos/$barrio_slug': typeof EventosBarrio_slugRoute
  '/listing/$id': typeof ListingIdRoute
  '/local-business/$barrio_slug': typeof LocalBusinessBarrio_slugRoute
  '/login_/verificar': typeof LoginVerificarRoute
  '/negocios/unirse': typeof NegociosUnirseRoute
  '/planes_/deal': typeof PlanesDealRoute
  '/planes_/featured-realtor': typeof PlanesFeaturedRealtorRoute
  '/planes_/hot-spot': typeof PlanesHotSpotRoute
  '/planes_/listing-member': typeof PlanesListingMemberRoute
  '/realtor/accept-invite': typeof RealtorAcceptInviteRoute
  '/realtor/agency-dashboard': typeof RealtorAgencyDashboardRoute
  '/realtor/dashboard': typeof RealtorDashboardRoute
  '/suscripcion/cancelada': typeof SuscripcionCanceladaRoute
  '/suscripcion/exito': typeof SuscripcionExitoRoute
  '/panel-x9k2/': typeof PanelX9k2IndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/afiliado'
    | '/agentes'
    | '/blog'
    | '/calculadora'
    | '/comparador'
    | '/comunidad'
    | '/conectar-agente'
    | '/embajador'
    | '/forgot-password'
    | '/login'
    | '/map'
    | '/mis-propiedades'
    | '/onboarding'
    | '/pasantias'
    | '/perfil'
    | '/planes'
    | '/publicar'
    | '/real-estate'
    | '/register'
    | '/reset-password'
    | '/simulador'
    | '/solicitudes'
    | '/stores'
    | '/suscribirse'
    | '/vender'
    | '/verify-email'
    | '/agentes/registro'
    | '/eventos/$barrio_slug'
    | '/listing/$id'
    | '/local-business/$barrio_slug'
    | '/login/verificar'
    | '/negocios/unirse'
    | '/planes/deal'
    | '/planes/featured-realtor'
    | '/planes/hot-spot'
    | '/planes/listing-member'
    | '/realtor/accept-invite'
    | '/realtor/agency-dashboard'
    | '/realtor/dashboard'
    | '/suscripcion/cancelada'
    | '/suscripcion/exito'
    | '/panel-x9k2/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/afiliado'
    | '/agentes'
    | '/blog'
    | '/calculadora'
    | '/comparador'
    | '/comunidad'
    | '/conectar-agente'
    | '/embajador'
    | '/forgot-password'
    | '/login'
    | '/map'
    | '/mis-propiedades'
    | '/onboarding'
    | '/pasantias'
    | '/perfil'
    | '/planes'
    | '/publicar'
    | '/real-estate'
    | '/register'
    | '/reset-password'
    | '/simulador'
    | '/solicitudes'
    | '/stores'
    | '/suscribirse'
    | '/vender'
    | '/verify-email'
    | '/agentes/registro'
    | '/eventos/$barrio_slug'
    | '/listing/$id'
    | '/local-business/$barrio_slug'
    | '/login/verificar'
    | '/negocios/unirse'
    | '/planes/deal'
    | '/planes/featured-realtor'
    | '/planes/hot-spot'
    | '/planes/listing-member'
    | '/realtor/accept-invite'
    | '/realtor/agency-dashboard'
    | '/realtor/dashboard'
    | '/suscripcion/cancelada'
    | '/suscripcion/exito'
    | '/panel-x9k2'
  id:
    | '__root__'
    | '/'
    | '/afiliado'
    | '/agentes'
    | '/blog'
    | '/calculadora'
    | '/comparador'
    | '/comunidad'
    | '/conectar-agente'
    | '/embajador'
    | '/forgot-password'
    | '/login'
    | '/map'
    | '/mis-propiedades'
    | '/onboarding'
    | '/pasantias'
    | '/perfil'
    | '/planes'
    | '/publicar'
    | '/real-estate'
    | '/register'
    | '/reset-password'
    | '/simulador'
    | '/solicitudes'
    | '/stores'
    | '/suscribirse'
    | '/vender'
    | '/verify-email'
    | '/agentes_/registro'
    | '/eventos/$barrio_slug'
    | '/listing/$id'
    | '/local-business/$barrio_slug'
    | '/login_/verificar'
    | '/negocios/unirse'
    | '/planes_/deal'
    | '/planes_/featured-realtor'
    | '/planes_/hot-spot'
    | '/planes_/listing-member'
    | '/realtor/accept-invite'
    | '/realtor/agency-dashboard'
    | '/realtor/dashboard'
    | '/suscripcion/cancelada'
    | '/suscripcion/exito'
    | '/panel-x9k2/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AfiliadoRoute: typeof AfiliadoRoute
  AgentesRoute: typeof AgentesRoute
  BlogRoute: typeof BlogRoute
  CalculadoraRoute: typeof CalculadoraRoute
  ComparadorRoute: typeof ComparadorRoute
  ComunidadRoute: typeof ComunidadRoute
  ConectarAgenteRoute: typeof ConectarAgenteRoute
  EmbajadorRoute: typeof EmbajadorRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  MapRoute: typeof MapRoute
  MisPropiedadesRoute: typeof MisPropiedadesRoute
  OnboardingRoute: typeof OnboardingRoute
  PasantiasRoute: typeof PasantiasRoute
  PerfilRoute: typeof PerfilRoute
  PlanesRoute: typeof PlanesRoute
  PublicarRoute: typeof PublicarRoute
  RealEstateRoute: typeof RealEstateRoute
  RegisterRoute: typeof RegisterRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SimuladorRoute: typeof SimuladorRoute
  SolicitudesRoute: typeof SolicitudesRoute
  StoresRoute: typeof StoresRoute
  SuscribirseRoute: typeof SuscribirseRoute
  VenderRoute: typeof VenderRoute
  VerifyEmailRoute: typeof VerifyEmailRoute
  AgentesRegistroRoute: typeof AgentesRegistroRoute
  EventosBarrio_slugRoute: typeof EventosBarrio_slugRoute
  ListingIdRoute: typeof ListingIdRoute
  LocalBusinessBarrio_slugRoute: typeof LocalBusinessBarrio_slugRoute
  LoginVerificarRoute: typeof LoginVerificarRoute
  NegociosUnirseRoute: typeof NegociosUnirseRoute
  PlanesDealRoute: typeof PlanesDealRoute
  PlanesFeaturedRealtorRoute: typeof PlanesFeaturedRealtorRoute
  PlanesHotSpotRoute: typeof PlanesHotSpotRoute
  PlanesListingMemberRoute: typeof PlanesListingMemberRoute
  RealtorAcceptInviteRoute: typeof RealtorAcceptInviteRoute
  RealtorAgencyDashboardRoute: typeof RealtorAgencyDashboardRoute
  RealtorDashboardRoute: typeof RealtorDashboardRoute
  SuscripcionCanceladaRoute: typeof SuscripcionCanceladaRoute
  SuscripcionExitoRoute: typeof SuscripcionExitoRoute
  PanelX9k2IndexRoute: typeof PanelX9k2IndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify-email': {
      id: '/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof VerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vender': {
      id: '/vender'
      path: '/vender'
      fullPath: '/vender'
      preLoaderRoute: typeof VenderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/suscribirse': {
      id: '/suscribirse'
      path: '/suscribirse'
      fullPath: '/suscribirse'
      preLoaderRoute: typeof SuscribirseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stores': {
      id: '/stores'
      path: '/stores'
      fullPath: '/stores'
      preLoaderRoute: typeof StoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solicitudes': {
      id: '/solicitudes'
      path: '/solicitudes'
      fullPath: '/solicitudes'
      preLoaderRoute: typeof SolicitudesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/simulador': {
      id: '/simulador'
      path: '/simulador'
      fullPath: '/simulador'
      preLoaderRoute: typeof SimuladorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/real-estate': {
      id: '/real-estate'
      path: '/real-estate'
      fullPath: '/real-estate'
      preLoaderRoute: typeof RealEstateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/publicar': {
      id: '/publicar'
      path: '/publicar'
      fullPath: '/publicar'
      preLoaderRoute: typeof PublicarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/planes': {
      id: '/planes'
      path: '/planes'
      fullPath: '/planes'
      preLoaderRoute: typeof PlanesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perfil': {
      id: '/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof PerfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pasantias': {
      id: '/pasantias'
      path: '/pasantias'
      fullPath: '/pasantias'
      preLoaderRoute: typeof PasantiasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mis-propiedades': {
      id: '/mis-propiedades'
      path: '/mis-propiedades'
      fullPath: '/mis-propiedades'
      preLoaderRoute: typeof MisPropiedadesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/map': {
      id: '/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof MapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/embajador': {
      id: '/embajador'
      path: '/embajador'
      fullPath: '/embajador'
      preLoaderRoute: typeof EmbajadorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conectar-agente': {
      id: '/conectar-agente'
      path: '/conectar-agente'
      fullPath: '/conectar-agente'
      preLoaderRoute: typeof ConectarAgenteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comunidad': {
      id: '/comunidad'
      path: '/comunidad'
      fullPath: '/comunidad'
      preLoaderRoute: typeof ComunidadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comparador': {
      id: '/comparador'
      path: '/comparador'
      fullPath: '/comparador'
      preLoaderRoute: typeof ComparadorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calculadora': {
      id: '/calculadora'
      path: '/calculadora'
      fullPath: '/calculadora'
      preLoaderRoute: typeof CalculadoraRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agentes': {
      id: '/agentes'
      path: '/agentes'
      fullPath: '/agentes'
      preLoaderRoute: typeof AgentesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/afiliado': {
      id: '/afiliado'
      path: '/afiliado'
      fullPath: '/afiliado'
      preLoaderRoute: typeof AfiliadoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/panel-x9k2/': {
      id: '/panel-x9k2/'
      path: '/panel-x9k2'
      fullPath: '/panel-x9k2/'
      preLoaderRoute: typeof PanelX9k2IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/suscripcion/exito': {
      id: '/suscripcion/exito'
      path: '/suscripcion/exito'
      fullPath: '/suscripcion/exito'
      preLoaderRoute: typeof SuscripcionExitoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/suscripcion/cancelada': {
      id: '/suscripcion/cancelada'
      path: '/suscripcion/cancelada'
      fullPath: '/suscripcion/cancelada'
      preLoaderRoute: typeof SuscripcionCanceladaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/realtor/dashboard': {
      id: '/realtor/dashboard'
      path: '/realtor/dashboard'
      fullPath: '/realtor/dashboard'
      preLoaderRoute: typeof RealtorDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/realtor/agency-dashboard': {
      id: '/realtor/agency-dashboard'
      path: '/realtor/agency-dashboard'
      fullPath: '/realtor/agency-dashboard'
      preLoaderRoute: typeof RealtorAgencyDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/realtor/accept-invite': {
      id: '/realtor/accept-invite'
      path: '/realtor/accept-invite'
      fullPath: '/realtor/accept-invite'
      preLoaderRoute: typeof RealtorAcceptInviteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/planes_/listing-member': {
      id: '/planes_/listing-member'
      path: '/planes/listing-member'
      fullPath: '/planes/listing-member'
      preLoaderRoute: typeof PlanesListingMemberRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/planes_/hot-spot': {
      id: '/planes_/hot-spot'
      path: '/planes/hot-spot'
      fullPath: '/planes/hot-spot'
      preLoaderRoute: typeof PlanesHotSpotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/planes_/featured-realtor': {
      id: '/planes_/featured-realtor'
      path: '/planes/featured-realtor'
      fullPath: '/planes/featured-realtor'
      preLoaderRoute: typeof PlanesFeaturedRealtorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/planes_/deal': {
      id: '/planes_/deal'
      path: '/planes/deal'
      fullPath: '/planes/deal'
      preLoaderRoute: typeof PlanesDealRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/negocios/unirse': {
      id: '/negocios/unirse'
      path: '/negocios/unirse'
      fullPath: '/negocios/unirse'
      preLoaderRoute: typeof NegociosUnirseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login_/verificar': {
      id: '/login_/verificar'
      path: '/login/verificar'
      fullPath: '/login/verificar'
      preLoaderRoute: typeof LoginVerificarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/local-business/$barrio_slug': {
      id: '/local-business/$barrio_slug'
      path: '/local-business/$barrio_slug'
      fullPath: '/local-business/$barrio_slug'
      preLoaderRoute: typeof LocalBusinessBarrio_slugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/listing/$id': {
      id: '/listing/$id'
      path: '/listing/$id'
      fullPath: '/listing/$id'
      preLoaderRoute: typeof ListingIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/eventos/$barrio_slug': {
      id: '/eventos/$barrio_slug'
      path: '/eventos/$barrio_slug'
      fullPath: '/eventos/$barrio_slug'
      preLoaderRoute: typeof EventosBarrio_slugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agentes_/registro': {
      id: '/agentes_/registro'
      path: '/agentes/registro'
      fullPath: '/agentes/registro'
      preLoaderRoute: typeof AgentesRegistroRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AfiliadoRoute: AfiliadoRoute,
  AgentesRoute: AgentesRoute,
  BlogRoute: BlogRoute,
  CalculadoraRoute: CalculadoraRoute,
  ComparadorRoute: ComparadorRoute,
  ComunidadRoute: ComunidadRoute,
  ConectarAgenteRoute: ConectarAgenteRoute,
  EmbajadorRoute: EmbajadorRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  MapRoute: MapRoute,
  MisPropiedadesRoute: MisPropiedadesRoute,
  OnboardingRoute: OnboardingRoute,
  PasantiasRoute: PasantiasRoute,
  PerfilRoute: PerfilRoute,
  PlanesRoute: PlanesRoute,
  PublicarRoute: PublicarRoute,
  RealEstateRoute: RealEstateRoute,
  RegisterRoute: RegisterRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SimuladorRoute: SimuladorRoute,
  SolicitudesRoute: SolicitudesRoute,
  StoresRoute: StoresRoute,
  SuscribirseRoute: SuscribirseRoute,
  VenderRoute: VenderRoute,
  VerifyEmailRoute: VerifyEmailRoute,
  AgentesRegistroRoute: AgentesRegistroRoute,
  EventosBarrio_slugRoute: EventosBarrio_slugRoute,
  ListingIdRoute: ListingIdRoute,
  LocalBusinessBarrio_slugRoute: LocalBusinessBarrio_slugRoute,
  LoginVerificarRoute: LoginVerificarRoute,
  NegociosUnirseRoute: NegociosUnirseRoute,
  PlanesDealRoute: PlanesDealRoute,
  PlanesFeaturedRealtorRoute: PlanesFeaturedRealtorRoute,
  PlanesHotSpotRoute: PlanesHotSpotRoute,
  PlanesListingMemberRoute: PlanesListingMemberRoute,
  RealtorAcceptInviteRoute: RealtorAcceptInviteRoute,
  RealtorAgencyDashboardRoute: RealtorAgencyDashboardRoute,
  RealtorDashboardRoute: RealtorDashboardRoute,
  SuscripcionCanceladaRoute: SuscripcionCanceladaRoute,
  SuscripcionExitoRoute: SuscripcionExitoRoute,
  PanelX9k2IndexRoute: PanelX9k2IndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
